"""Generate a self-contained HTML digest page from enriched article items."""

from __future__ import annotations

from pathlib import Path

_TAG_COLOURS = {
    "ai":         ("#e8f0fe", "#1a73e8"),
    "technology": ("#e6f4ea", "#137333"),
    "science":    ("#fce8b2", "#b06000"),
    "business":   ("#fce8e6", "#c5221f"),
    "world":      ("#f3e8fd", "#7b1fa2"),
    "politics":   ("#feefc3", "#b06000"),
    "health":     ("#e6f4ea", "#137333"),
    "climate":    ("#e8f5e9", "#2e7d32"),
    "security":   ("#fce8e6", "#c62828"),
    "culture":    ("#f8f0fb", "#6a1b9a"),
    "other":      ("#f1f3f4", "#5f6368"),
}

def _tag_badge(tag: str) -> str:
    bg, fg = _TAG_COLOURS.get(tag.lower(), _TAG_COLOURS["other"])
    return (
        f'<span style="background:{bg};color:{fg};padding:2px 9px;border-radius:12px;'
        f'font-size:0.72rem;font-weight:600;margin-right:4px">{tag}</span>'
    )


def _stars(importance: int) -> str:
    n = max(1, min(5, int(importance)))
    return "★" * n + "☆" * (5 - n)


def _article_card(item: dict, large: bool = False) -> str:
    title   = item.get("title", "Untitled")
    url     = item.get("url", "#")
    source  = item.get("source", "")
    pub     = (item.get("published_at") or "")[:10]
    summary = item.get("summary", "")
    tags    = item.get("tags") or []
    imp     = item.get("importance", 3)

    badges  = "".join(_tag_badge(t) for t in tags)
    stars   = _stars(imp)
    padding = "20px 24px" if large else "16px 20px"
    title_size = "1.05rem" if large else "0.95rem"

    return f"""
<div style="background:#fff;border:1px solid #e0e0e0;border-radius:10px;
            padding:{padding};margin-bottom:16px;box-shadow:0 1px 3px rgba(0,0,0,.06)">
  <div style="display:flex;justify-content:space-between;align-items:flex-start;
              margin-bottom:6px">
    <a href="{url}" target="_blank" rel="noopener"
       style="font-size:{title_size};font-weight:700;color:#1a1a1a;
              text-decoration:none;line-height:1.4;flex:1;margin-right:12px"
       onmouseover="this.style.color='#1a73e8'"
       onmouseout="this.style.color='#1a1a1a'">{title}</a>
    <span style="font-size:0.85rem;color:#f9a825;white-space:nowrap;
                 letter-spacing:1px" title="Importance {imp}/5">{stars}</span>
  </div>
  <div style="font-size:0.78rem;color:#888;margin-bottom:8px">
    {source} &nbsp;·&nbsp; {pub}
  </div>
  {"<p style='font-size:0.88rem;color:#333;line-height:1.6;margin:0 0 10px'>" + summary + "</p>" if summary else ""}
  <div>{badges}</div>
</div>"""


def write_html(output_dir: Path, date_str: str, enriched_items: list[dict]) -> Path:
    """Write a styled HTML digest to output_dir/YYYY-MM-DD.html. Returns the path."""
    output_dir.mkdir(parents=True, exist_ok=True)

    items = sorted(enriched_items, key=lambda x: x.get("importance", 3), reverse=True)
    max_top = 5
    top  = items[:max_top]
    rest = items[max_top:]

    # Group rest by first tag
    by_tag: dict[str, list[dict]] = {}
    for it in rest:
        tag = (it.get("tags") or ["other"])[0].lower()
        by_tag.setdefault(tag, []).append(it)

    top_html = "\n".join(_article_card(it, large=True) for it in top)

    more_html = ""
    for tag, tag_items in sorted(by_tag.items()):
        cards = "\n".join(_article_card(it) for it in tag_items)
        more_html += f"""
<h2 style="font-size:1rem;font-weight:700;color:#444;margin:28px 0 12px;
           text-transform:uppercase;letter-spacing:.08em;
           border-bottom:2px solid #e8f0fe;padding-bottom:6px">{tag.title()}</h2>
{cards}"""

    count = len(enriched_items)
    empty_msg = '<p style="color:#888;text-align:center;padding:40px 0">No new articles today.</p>'

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>News Buddy — {date_str}</title>
<style>
  *, *::before, *::after {{ box-sizing: border-box; }}
  body {{
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
    background: #f8f9fa;
    color: #1a1a1a;
    margin: 0;
    padding: 0;
  }}
  .wrap {{ max-width: 760px; margin: 0 auto; padding: 24px 16px 60px; }}
  @media (max-width: 600px) {{ .wrap {{ padding: 16px 12px 40px; }} }}
</style>
</head>
<body>
<div class="wrap">

  <!-- Header -->
  <div style="background:linear-gradient(135deg,#1a73e8,#0d47a1);color:#fff;
              border-radius:12px;padding:24px 28px;margin-bottom:28px">
    <div style="font-size:0.8rem;opacity:.8;margin-bottom:4px;letter-spacing:.05em">
      DAILY AI NEWS
    </div>
    <h1 style="margin:0 0 6px;font-size:1.6rem;font-weight:800">{date_str}</h1>
    <div style="font-size:0.85rem;opacity:.85">{count} article{"s" if count != 1 else ""} · Generated by News Buddy</div>
  </div>

  {f'''
  <!-- Top Stories -->
  <h2 style="font-size:1rem;font-weight:700;color:#444;margin:0 0 14px;
             text-transform:uppercase;letter-spacing:.08em;
             border-bottom:2px solid #e8f0fe;padding-bottom:6px">Top Stories</h2>
  {top_html}
  {more_html}
  ''' if enriched_items else empty_msg}

  <!-- Footer -->
  <div style="text-align:center;font-size:0.75rem;color:#aaa;margin-top:40px">
    News Buddy &nbsp;·&nbsp; {date_str} &nbsp;·&nbsp;
    <a href="https://github.com/Harshagarwal06/buddy_agent"
       style="color:#aaa" target="_blank">source</a>
  </div>

</div>
</body>
</html>"""

    target = output_dir / f"{date_str}.html"
    tmp = target.with_suffix(".html.tmp")
    tmp.write_text(html, encoding="utf-8")
    tmp.replace(target)
    return target
